#!/bin/bash
yum install git
cd /root
git clone -b manyuser https://github.com/shadowsocksr/shadowsocksr.git
cd ~/shadowsocksr
bash initcfg.sh
cd ~/shadowsocksr/shadowsocks
python server.py -p 8070 -k password -m Gq19940507+ -O origin -o http_simple -d star
IP=$(ip addr | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | egrep -v "^192\.168|^172\.1[6-9]\.|^172\.2[0-9]\.|^172\.3[0-2]\.|^10\.|^127\.|^255\.|^0\." | head -n 1)
if [[ "$IP" = "" ]]; then
    IP=$(wget -qO- -t1 -T2 ipv4.icanhazip.com)
fi
 echo
        echo "恭喜你！我们已为你完成了所有的安装，以下是连接信息！"
        echo -e "服务器IP地址: \033[41;37m ${IP} \033[0m"
        echo -e "远程端口: 8070"
        echo -e "密码: Gq19940507+"
        echo -e "本地IP地址: \033[41;37m 127.0.0.1 \033[0m"
        echo -e "本地端口: \033[41;37m 1080 \033[0m"
        echo -e "认证协议: origin"
        echo -e "混淆方式: http_simple"
        echo -e "加密方法: aes-256-cfb"
echo
