#!/bin/bash
yum install git
cd /root
git clone -b manyuser https://github.com/shadowsocksr/shadowsocksr.git
cd ~/shadowsocksr
bash initcfg.sh
cd ~/shadowsocksr/shadowsocks
python server.py -p 8080 -k password -m Gq19940507+ -O origin -o http_simple -d star
